const CONTENT_TYPE_ARTICLE='CONTENT_TYPE_ARTICLE'
const CONTENT_TYPE_QUIZZ='CONTENT_TYPE_QUIZZ'
const CONTENT_TYPE_BESTPRACTICES='CONTENT_TYPE_BESTPRACTICES'
const CONTENT_TYPE_EMERGENCY='CONTENT_TYPE_EMERGENCY'
const CONTENT_TYPE_MODULE='CONTENT_TYPE_MODULE'
const CONTENT_TYPE_TIP='CONTENT_TYPE_TIP'

const CONTENT_TYPE={
  [CONTENT_TYPE_ARTICLE]: 'Article',
  [CONTENT_TYPE_QUIZZ]: 'Quizz',
  [CONTENT_TYPE_BESTPRACTICES]: 'Best practices',
  [CONTENT_TYPE_EMERGENCY]: 'Urgence',
  [CONTENT_TYPE_MODULE]: 'Module',
  [CONTENT_TYPE_TIP]: 'Le saviez-vous?',
}

const QUESTION_TYPE_TEXT='QUESTION_TYPE_TEXT'
const QUESTION_TYPE_NUMERIC='QUESTION_TYPE_NUMERIC'
const QUESTION_TYPE_ENUM_SINGLE='QUESTION_TYPE_ENUM_SINGLE'
const QUESTION_TYPE_ENUM_MULTIPLE='QUESTION_TYPE_ENUM_MULTIPLE'
const QUESTION_TYPE_TEXT_MULTIPLE='QUESTION_TYPE_TEXT_MULTIPLE'

const QUESTION_TYPE={
  [QUESTION_TYPE_TEXT]: 'Texte libre',
  [QUESTION_TYPE_NUMERIC]: 'Numérique libre',
  [QUESTION_TYPE_ENUM_SINGLE]: 'QCM une réponse',
  [QUESTION_TYPE_ENUM_MULTIPLE]: 'QCM plusieurs réponses',
  [QUESTION_TYPE_TEXT_MULTIPLE]: 'Texte multiple',
}

const SEASON_SPRING="SEASON_SPRING"
const SEASON_SUMMER="SEASON_SUMMER"
const SEASON_AUTUMMN="SEASON_AUTUMMN"
const SEASON_WINTER="SEASON_WINTER"

const SEASON={
  [SEASON_SPRING]:"Printemps",
  [SEASON_SUMMER]:"Été",
  [SEASON_AUTUMMN]:"Automne",
  [SEASON_WINTER]:"Hiver",
}

module.exports={
  CONTENT_TYPE,
  QUESTION_TYPE,
  SEASON,
}
