const EXCAVATRICE='EXCAVATRICE'
const CHARGEUSE='CHARGEUSE'
const PELLE_BUTTE='PELLE-BUTTE'
const UNKNOWN='UNKNOWN'

const MACHINE_TYPES={
  [EXCAVATRICE]: 'MACHINE_TYPE.excavator',
  [CHARGEUSE]: 'MACHINE_TYPE.loader',
  [PELLE_BUTTE]: 'MACHINE_TYPE.shovel',
}

const PIN='PIN'
const SOLD='SOLD'

const FIX_TYPES={
  [PIN]: 'FIX_TYPE.pin',
  [SOLD]: 'FIX_TYPE.sold',
}

const DROITE='DROITE'
const DELTA='DELTA'
const SEMI_DELTA='SEMI-DELTA'

const BLADE_SHAPES={
  [DROITE]: 'BLADE_SHAPE.straight',
  [DELTA]: 'BLADE_SHAPE.delta',
  [SEMI_DELTA]: 'BLADE_SHAPE.semi_delta',
  [UNKNOWN]: 'BLADE_SHAPE.unknown',
}

/**
Quotation & book status :
- Quotation: CREATED, HANDLED, EXPIRED,
- Booking: CREATED, PARTIALLY_HANDLED, HANDLED
*/

const QUOTATION_STATUS={
  CREATED: 'QUOTATION_STATUS.created',
  HANDLED: 'QUOTATION_STATUS.handled',
  EXPIRED: 'QUOTATION_STATUS.expired',
}

const BOOK_STATUS={
  CREATED: 'BOOKING_STATUS.created',
  PARTIALLY_HANDLED: 'BOOKING_STATUS.partially_handled',
  FULLY_HANDLED: 'BOOKING_STATUS.partially_handled',
}

const FEURST_ADMIN='FEURST_ADMIN'
const FEURST_ADV='FEURST_ADV'
const CUSTOMER_MASTER='CUSTOMER_MASTER'
const CUSTOMER_SLAVE='CUSTOMER_SLAVE'


const ROLES = {
  [FEURST_ADMIN]: 'Administrateur Feurst',
  [FEURST_ADV]: 'ADV',
  [CUSTOMER_MASTER]: 'Administrateur client',
  [CUSTOMER_SLAVE]: 'Client',
}

module.exports={
  PIN, SOLD, FIX_TYPES,
  DROITE, DELTA, SEMI_DELTA, UNKNOWN, BLADE_SHAPES,
  EXCAVATRICE, CHARGEUSE, PELLE_BUTTE, MACHINE_TYPES,
  BOOK_STATUS, QUOTATION_STATUS, FEURST_ADMIN, FEURST_ADV, CUSTOMER_MASTER, CUSTOMER_SLAVE,
  ROLES,
}
