const ROLE_ADMIN='ROLE_ADMIN'
const ROLE_CUSTOMER='ROLE_CUSTOMER'
const ROLE_DEV='ROLE_DEV'
const ROLE_VALID='ROLE_VALID'

const ROLES={
  [ROLE_ADMIN]:'Admministrateur',
  [ROLE_CUSTOMER]:'Client',
  [ROLE_DEV]:'Développeur',
  [ROLE_VALID]:'Valideur',
}

const ISSUE_STATUS_NEW="ISSUE_STATUS_NEW"
const ISSUE_STATUS_OPEN="ISSUE_STATUS_OPEN"
const ISSUE_STATUS_IN_PROGRESS="ISSUE_STATUS_IN_PROGRESS"
const ISSUE_STATUS_CLOSED="ISSUE_STATUS_CLOSED"
const ISSUE_STATUS_REJECTED="ISSUE_STATUS_REJECTED"
const ISSUE_STATUS_INTERNAL_VALIDATION="ISSUE_STATUS_INTERNAL_VALIDATION"
const ISSUE_STATUS_INTERNAL_VALID="ISSUE_STATUS_INTERNAL_VALID"
const ISSUE_STATUS_CUSTOMER_VALIDATION="ISSUE_STATUS_CUSTOMER_VALIDATION"
const ISSUE_STATUS_CUSTOMER_VALID="ISSUE_STATUS_CUSTOMER_VALID"

const ISSUE_STATUS={
  [ISSUE_STATUS_NEW]:"Nouveau",
  [ISSUE_STATUS_OPEN]:"Ouvert",
  [ISSUE_STATUS_IN_PROGRESS]:"En développement",
  [ISSUE_STATUS_CLOSED]:"Fermé",
  [ISSUE_STATUS_REJECTED]:"Rejeté",
  [ISSUE_STATUS_INTERNAL_VALIDATION]:"Validation interne",
  [ISSUE_STATUS_INTERNAL_VALID]:"Validé interne",
  [ISSUE_STATUS_CUSTOMER_VALIDATION]:"Validaiton client",
  [ISSUE_STATUS_CUSTOMER_VALID]:"Validé client",
}

module.exports={
 ROLES,
 ISSUE_STATUS,
}
