const STATUS_SOLO='SOLO'
const STATUS_COUPLE='COUPLE'
const STATUS_FAMILY='FAMILY'
const STATUS_FLATSHARING='FLATSHARING'

const HOME_STATUS = {
  [STATUS_SOLO]: 'Solo',
  [STATUS_COUPLE]: 'Couple',
  [STATUS_FAMILY]: 'Famille',
  [STATUS_FLATSHARING]: 'Colocation',
}

const CONTENTS_ARTICLE= 'ARTICLE'
const CONTENTS_INFOGRAPHY='INFOGRAPHY'
const CONTENTS_VIDEO='VIDEO'
const CONTENTS_PODCAST='PODCAST'

const CONTENTS_TYPE = {
  [CONTENTS_ARTICLE]: 'Article',
  [CONTENTS_VIDEO]: 'Vidéo',
  [CONTENTS_INFOGRAPHY]: 'Infography',
  [CONTENTS_PODCAST]: 'Podcast',
}

const EVENT_MENU= 'MENU'
const EVENT_IND_CHALLENGE='IND_CHALLENGE'
const EVENT_COLL_CHALLENGE='COLL_CHALLENGE'
const EVENT_WEBINAR='WEBINAR'
const EVENT_QUIZZ='QUIZZ'

const EVENT_TYPE = {
  [EVENT_MENU]: 'Menu',
  [EVENT_IND_CHALLENGE]: 'Challenge individuel',
  [EVENT_COLL_CHALLENGE]: 'Challenge collectif',
  [EVENT_WEBINAR]: 'Webinaire',
  [EVENT_QUIZZ]: 'Quizz',
}

const ROLE_CUSTOMER='CUSTOMER'
const ROLE_RH='RH'
const ROLE_DIET='DIET'
const ROLE_SUPER_ADMIN='SUPER_ADMIN'
const ROLE_ADMIN='ADMIN'
const ROLE_SUPPORT='SUPPORT'

const ROLES={
  [ROLE_CUSTOMER]: 'Abonné',
  [ROLE_RH]: 'RH',
  [ROLE_DIET]: 'Diététicien(ne)',
  [ROLE_SUPER_ADMIN]: 'Superadministrateur',
  [ROLE_ADMIN]: 'Administrateur',
  [ROLE_SUPPORT]: 'Support',
}

const GENDER_MALE='MALE'
const GENDER_FEMALE='FEMALE'
const GENDER_NON_BINARY='NON_BINARY'

const GENDER = {
  [GENDER_MALE]: 'Homme',
  [GENDER_FEMALE]: 'Femme',
  [GENDER_NON_BINARY]: 'Non genré',
}

const ACT_ACTIVE='ACTIVE'
const ACT_STUDENT='STUDENT'
const ACT_RETIRED='RETIRED'
const ACT_OTHER='OTHER'

const ACTIVITY={
  [ACT_ACTIVE]: 'Actif',
  [ACT_STUDENT]: 'Etudiant',
  [ACT_RETIRED]: 'En retraite',
  [ACT_OTHER]: 'Autre',
}

const TARGET_OBJECTIVE='OBJECTIVE'
const TARGET_SPECIFICITY='SPECIFICITY'

const TARGET_TYPE={
  [TARGET_OBJECTIVE]: 'Objectif',
  [TARGET_SPECIFICITY]: 'Spécificité',
}

module.exports={
  HOME_STATUS,
  CONTENTS_TYPE,
  EVENT_TYPE,
  ROLES,
  GENDER,
  ACTIVITY,
  TARGET_TYPE,
}
