const GENDER_MALE='MALE'
const GENDER_FEMALE='FEMALE'

const GENDER = {
  [GENDER_MALE]: 'Homme',
  [GENDER_FEMALE]: 'Femme',
}

const APPOINTMENT_CARDIOLOGIST='CARDIO'
const APPOINTMENT_GENERALIST='GENERAL'
const APPOINTMENT_OTHER='OTHER'

const APPOINTMENT_TYPE={
  [APPOINTMENT_CARDIOLOGIST]: 'Cardiologue',
  [APPOINTMENT_GENERALIST]: 'Généraliste',
  [APPOINTMENT_OTHER]: 'Autre',
}

const REMINDER_BLOOD_PRESSURE='BLOOD_PRESSURE'
const REMINDER_MEDICATION='MEDICATIONS'
const REMINDER_OTHER='OTHER'

const REMINDER_TYPE={
  [REMINDER_BLOOD_PRESSURE]: 'Prise de tension',
  [REMINDER_MEDICATION]: 'Prise de médicaments',
  [REMINDER_OTHER]: 'Autre',
}

const SMOKER_CURRENT='SMOKER_CURRENT'
const SMOKER_STOPPED='SMOKER_STOPPED'
const SMOKER_NEVER='SMOKER_NEVER'

const SMOKER_TYPE={
  [SMOKER_CURRENT]: 'Je fume',
  [SMOKER_STOPPED]: 'J\'ai arrêté de fumer',
  [SMOKER_NEVER]: 'Je n\'ai jamais fumé',
}

const WITHINGS_MEASURE_DIA=9
const WITHINGS_MEASURE_SYS=10
const WITHINGS_MEASURE_BPM=11

const MEASURE_MANUAL='MANUAL'
const MEASURE_AUTO='AUTO'

const MEASURE_SOURCE={
  [MEASURE_MANUAL]: 'Manuelle',
  [MEASURE_AUTO]: 'Automatique',
}

module.exports={
  GENDER, GENDER_MALE, GENDER_FEMALE,
  APPOINTMENT_TYPE, APPOINTMENT_OTHER,
  REMINDER_TYPE, REMINDER_OTHER, REMINDER_MEDICATION,
  SMOKER_TYPE,
  WITHINGS_MEASURE_DIA, WITHINGS_MEASURE_SYS, WITHINGS_MEASURE_BPM,
  MEASURE_SOURCE, MEASURE_AUTO,MEASURE_MANUAL,
}
