import {
  CloseButton,
  Heading,
  Textarea,
  Spinner,
  Code,
  Link,
  Progress,
  Text,
  Image,
  Icon,
  IconButton,
  Button,
  Box,
  Badge,
  Tag,
  SimpleGrid,
  Switch,
  CircularProgress,
  Checkbox,
  AvatarBadge,
  AvatarGroup,
  Avatar
} from "@chakra-ui/core";

export const DEFAULT_PROPS: PreviewDefaultProps = {
  Badge: Badge.defaultProps,
  Box: Box.defaultProps,
  Button: Button.defaultProps,
  IconButton: IconButton.defaultProps,
  Icon: Icon.defaultProps,
  Image: Image.defaultProps,
  Text: Text.defaultProps,
  Progress: Progress.defaultProps,
  Link: Link.defaultProps,
  Code: Code.defaultProps,
  Spinner: Spinner.defaultProps,
  TextArea: Textarea.defaultProps,
  Heading: Heading.defaultProps,
  CloseButton: CloseButton.defaultProps,
  Tag: Tag.defaultProps,
  SimpleGrid: SimpleGrid.defaultProps,
  Switch: Switch.defaultProps,
  CircularProgress: CircularProgress.defaultProps,
  Checkbox: Checkbox.defaultProps,
  AvatarBadge: AvatarBadge.defaultProps,
  AvatarGroup: AvatarGroup.defaultProps,
  Avatar: Avatar.defaultProps
};
