"""Nullable prospect attributes

Revision ID: 3e901dc99810
Revises: d99ddbbb7405
Create Date: 2019-06-30 14:05:51.940490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e901dc99810'
down_revision = 'd99ddbbb7405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prospect', 'address',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('prospect', 'announce_url',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('prospect', 'name',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('prospect', 'post_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('prospect', 'title',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prospect', 'title',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('prospect', 'post_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('prospect', 'name',
               existing_type=mysql.TEXT(),
               nullable=False)
    op.alter_column('prospect', 'announce_url',
               existing_type=mysql.TEXT(),
               nullable=True)
    op.alter_column('prospect', 'address',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
