# Certificats avec Certbot (Let's Encrypt)

## Installation

[source, bash]
----
$ sudo dnf install certbot
----


## Génération du certificat (manual)

[source, bash]
----
$ sudo certbot certonly --manual --preferred-challenges=dns -d <domaine> -d <sous-domaine1>
----

1. On est amené à renseigner les domaines (ex: *.all-entrepreneurs.fr www.all-entrepreneurs.fr)
2. --preferred-challenges=dns permet de valider le domaine par des entrées TXT dans le dns,
plus simple que rendre disponibles des fichiers dans http://<domain>/acme_challenge...
3. Génération des certificats

[source, bash]
----
Certificate is saved at: /etc/letsencrypt/live/all-entrepreneurs.fr/fullchain.pem
Key is saved at:         /etc/letsencrypt/live/all-entrepreneurs.fr/privkey.pem
----

Copier ces 2 fichiers dans le dossier ~/.ssh et changer le propriétaire:

chown ec2-user:ec2-user ~/.ssh/*.pem

## Config serveur

Modification en conséquence du fichier _server.js_ (un fois seulement)

IMPORTANT: Le fichier n'est pas versionné actuellement

[source, bash]
.web/server/server.js
----

// HTTPS server using certificates
const httpsServer = https.createServer({
  cert: fs.readFileSync(`${process.env.HOME}/.ssh/fullchain.pem`),
  key: fs.readFileSync(`${process.env.HOME}/.ssh/privkey.pem`),
},
app)

----

## Rédémarrage serveurs

pm2 restart all && sudo systemectl restart nginx

## TODO
Je l'ai fait avec l'option --manual, mais il y a moyen de mettre en place le renouvellement auto du certificat.

Pour cela, passer en paramètre de certbot le script ajoutant l'entrée TXT dans le DNS (voir le package certbot-ovh ou le package ovh de node)
