
# My-Alfred

## Bases

On remonte les bases régulièrement. 

Dans myAlfred/web/scripts

[, bash]
----
sh resetdb.sh
----


## Fautes 

Globalement, on peut tout corriger, dans les fichiers de config


## Inscription côté proposition services


### Process inscription sans url

Un retour historique sème la pagaille. Voir pour mettre toutes les données passées dans le state, dans du localStorage 


## Problèmes navigation relevés

### Calendrier 

bug lors clic sur dates du calendrier (problème avec current ?)


### Commits 

rpa-


## Sites

Le service de base, my-alfred.io, en b to c.

2 fonctions : 

marketplace et plateforme (réserve un service)

3122 : site validation client all inclusive



3123 : All-inclusive. plateforme. On réserve un service. Cela fait 2 réservations. Une pour l'admin. Et...

### Avocotés 

https://my-alfred.io/avocotes

Permet de réserver pour une installation de télésurveillance.


## BDD :

test-myalfred pour la production 
test-myalfred-v2  pour la validation


## Images 

Les images sont pas resizées actuellement. Si une nouvelle image est envoyée, l'ancienne n'est pas supprimée.


## RGPD

Suppression du compte possible. Mais reste des données. TODO




Je dois prendre le slider, avec tous ses slides.





 <script>
    
    $('.dot').each(function() {
        $(this).on('click', function(e) {
        

  /* Si y'a pas de class active */
  if (!$(this).hasClass('active')) {
    var $this = $(this);
    me.slider_acc.find('.slide:visible').fadeOut('slow', function() {
      me.slider_show_slide($this.index() + 1);
    });

    me.slider_acc.find('.dot.active').removeClass('active');
    var new_active = $(this).index();
    me.slider_acc.find('.dots').each(function() {
      $('.dot', $(this)).eq(new_active).addClass('active');
    });
  }
    
    })
})
    </script>




2 (initial) boucliers à 4