const GDR_MALE='MALE'
const GDR_FEMALE='FEMALE'

const GENDER = {
  [GDR_MALE]: 'Homme',
  [GDR_FEMALE]: 'Femme',
}

const MEASURE_BLOOD_PRESURE='BLOOD_PRESSURE'
const MEASURE_HEARTBEAT='HEARTBEAT'

const MEASURE_TYPE={
  [MEASURE_BLOOD_PRESURE]: 'Prise de tension',
  [MEASURE_HEARTBEAT]: 'Prise de rythme cardiaque',
}

const APPOINTMENT_CARDIOLOGIST='CARDIO'
const APPOINTMENT_GENERALIST='GENERAL'
const APPOINTMENT_OTHER='OTHER'

const APPOINTMENT_TYPE={
  [APPOINTMENT_CARDIOLOGIST]: 'Cardiologue',
  [APPOINTMENT_GENERALIST]: 'Généraliste',
  [APPOINTMENT_OTHER]: 'Autre',
}

const REMINDER_BLOOD_PRESSURE='BLOOD_PRESSURE'
const REMINDER_MEDICATION='MEDICATIONS'
const REMINDER_OTHER='OTHER'

const REMINDER_TYPE={
  [REMINDER_BLOOD_PRESSURE]: 'Prise de tension',
  [REMINDER_MEDICATION]: 'Prise de médicaments',
  [REMINDER_OTHER]: 'Autre',
}

const SMOKER_CURRENT='SMOKER_CURRENT'
const SMOKER_STOPPED='SMOKER_STOPPED'
const SMOKER_NEVER='SMOKER_NEVER'

const SMOKER_TYPE={
  [SMOKER_CURRENT]: 'Je fume',
  [SMOKER_STOPPED]: 'J\'ai arrêté de fumer',
  [SMOKER_NEVER]: 'Je n\'ai jamais fumé',
}

module.exports={
  GENDER, GDR_MALE, 
  MEASURE_TYPE,
  APPOINTMENT_TYPE, APPOINTMENT_OTHER,
  REMINDER_TYPE, REMINDER_OTHER,
  SMOKER_TYPE,
}
