const MODE = 'validation';
const DISABLE_ALFRED_SELF_REGISTER=true
const DISABLE_ALFRED_PARTICULAR_REGISTER=true
const HIDE_EMPTY_EVALUATIONS=true
const SIB_TEMPLATES='all-inclusive'
const DATABASE_NAME='aftral'
const MANGOPAY_CLIENTID='testmyalfredv2'
const MANGOPAY_APIKEY='cSNrzHm5YRaQxTdZVqWxWAnyYDphvg2hzBVdgTiAOLmgxvF2oN'
const SITE_MODE='platform'
const IGNORE_FAILED_PAYMENT=true

module.exports = {MODE, DISABLE_ALFRED_SELF_REGISTER, DISABLE_ALFRED_PARTICULAR_REGISTER, HIDE_EMPTY_EVALUATIONS, SIB_TEMPLATES, DATABASE_NAME,
MANGOPAY_CLIENTID, MANGOPAY_APIKEY, SITE_MODE, IGNORE_FAILED_PAYMENT}

