const MODE = 'validation';
const DISABLE_ALFRED_SELF_REGISTER=true
const DISABLE_ALFRED_PARTICULAR_REGISTER=true
const HIDE_EMPTY_EVALUATIONS=true
const DATABASE_NAME='aftral'
const MANGOPAY_CLIENTID='testmyalfredv2'
const MANGOPAY_APIKEY='cSNrzHm5YRaQxTdZVqWxWAnyYDphvg2hzBVdgTiAOLmgxvF2oN'
const SITE_MODE='platform'
const SKIP_FAILED_PAYMENT=true
const URL_BASEPATH = 'https://localhost'
const MONO_PROVIDER = true

module.exports = {MODE, DISABLE_ALFRED_SELF_REGISTER, DISABLE_ALFRED_PARTICULAR_REGISTER, HIDE_EMPTY_EVALUATIONS, DATABASE_NAME,
MANGOPAY_CLIENTID, MANGOPAY_APIKEY, SITE_MODE, SKIP_FAILED_PAYMENT, URL_BASEPATH, MONO_PROVIDER}

